### ISSUE TITLE
Read the docs needs explicit conf.py path now

### ISSUE THREAD

**Issue by NiklasDerEchte** [NiklasDerEchte/GameCore#1]
Add this to readthedocs.yml

```
sphinx:
  configuration: docs/conf.py
```

like:

```
version: 2

sphinx: <---- here
  configuration: docs/conf.py

build:
 os: ubuntu-24.04

...

```
